{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 51,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "W0615 14:06:08.267000 8404925120 torch/distributed/elastic/multiprocessing/redirects.py:27] NOTE: Redirects are currently not supported in Windows or MacOs.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/karahansahin/Documents/Research/sign2vec/pretraining/run_sign2vec_pretraining.py\", line 64, in <module>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/karahansahin/Documents/Research/sign2vec/pretraining/run_sign2vec_pretraining.py\", line 64, in <module>\n",
      "        main()\n",
      "main()\n",
      "  File \"/Users/karahansahin/Documents/Research/sign2vec/pretraining/run_sign2vec_pretraining.py\", line 30, in main\n",
      "  File \"/Users/karahansahin/Documents/Research/sign2vec/pretraining/run_sign2vec_pretraining.py\", line 30, in main\n",
      "    accelerator, api, repo_id = initialize_accelerator(args)\n",
      "              accelerator, api, repo_id = initialize_accelerator(args) \n",
      "                                             ^^^^^^^^    ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "^^^^  File \"/Users/karahansahin/Documents/Research/sign2vec/pretraining/utils/accelerator.py\", line 17, in initialize_accelerator\n",
      "^^^^^^^^\n",
      "  File \"/Users/karahansahin/Documents/Research/sign2vec/pretraining/utils/accelerator.py\", line 17, in initialize_accelerator\n",
      "    accelerator = Accelerator()\n",
      "                  ^^^^^^^^^^^^^\n",
      "    accelerator = Accelerator()  File \"/opt/anaconda3/lib/python3.11/site-packages/accelerate/accelerator.py\", line 316, in __init__\n",
      "\n",
      "                  ^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.11/site-packages/accelerate/accelerator.py\", line 316, in __init__\n",
      "    FullyShardedDataParallelPlugin() if os.environ.get(\"ACCELERATE_USE_FSDP\", \"false\") == \"true\" else None\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<string>\", line 18, in __init__\n",
      "  File \"/opt/anaconda3/lib/python3.11/site-packages/accelerate/utils/dataclasses.py\", line 1168, in __post_init__\n",
      "    FullyShardedDataParallelPlugin() if os.environ.get(\"ACCELERATE_USE_FSDP\", \"false\") == \"true\" else None\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<string>\", line 18, in __init__\n",
      "  File \"/opt/anaconda3/lib/python3.11/site-packages/accelerate/utils/dataclasses.py\", line 1168, in __post_init__\n",
      "    raise RuntimeError(    raise RuntimeError(\n",
      "\n",
      "RuntimeError: There are currently no available devices found, must be one of 'XPU', 'CUDA', or 'NPU'.RuntimeError: \n",
      "There are currently no available devices found, must be one of 'XPU', 'CUDA', or 'NPU'.\n",
      "E0615 14:06:13.304000 8404925120 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 85229) of binary: /opt/anaconda3/bin/python\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/bin/accelerate\", line 8, in <module>\n",
      "    sys.exit(main())\n",
      "             ^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py\", line 48, in main\n",
      "    args.func(args)\n",
      "  File \"/opt/anaconda3/lib/python3.11/site-packages/accelerate/commands/launch.py\", line 1084, in launch_command\n",
      "    multi_gpu_launcher(args)\n",
      "  File \"/opt/anaconda3/lib/python3.11/site-packages/accelerate/commands/launch.py\", line 733, in multi_gpu_launcher\n",
      "    distrib_run.run(args)\n",
      "  File \"/opt/anaconda3/lib/python3.11/site-packages/torch/distributed/run.py\", line 870, in run\n",
      "    elastic_launch(\n",
      "  File \"/opt/anaconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py\", line 132, in __call__\n",
      "    return launch_agent(self._config, self._entrypoint, list(args))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py\", line 263, in launch_agent\n",
      "    raise ChildFailedError(\n",
      "torch.distributed.elastic.multiprocessing.errors.ChildFailedError: \n",
      "============================================================\n",
      "run_sign2vec_pretraining.py FAILED\n",
      "------------------------------------------------------------\n",
      "Failures:\n",
      "[1]:\n",
      "  time      : 2024-06-15_14:06:13\n",
      "  host      : Karahans-MacBook-Pro.local\n",
      "  rank      : 1 (local_rank: 1)\n",
      "  exitcode  : 1 (pid: 85230)\n",
      "  error_file: <N/A>\n",
      "  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html\n",
      "------------------------------------------------------------\n",
      "Root Cause (first observed failure):\n",
      "[0]:\n",
      "  time      : 2024-06-15_14:06:13\n",
      "  host      : Karahans-MacBook-Pro.local\n",
      "  rank      : 0 (local_rank: 0)\n",
      "  exitcode  : 1 (pid: 85229)\n",
      "  error_file: <N/A>\n",
      "  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html\n",
      "============================================================\n"
     ]
    }
   ],
   "source": [
    "!accelerate launch run_sign2vec_pretraining.py \\\n",
    "\t\t\t\t\t\t--model_name_or_path=\"patrickvonplaten/wav2vec2-base-v2\" \\\n",
    "\t\t\t\t\t\t--output_dir=\"./sign2vec\" \\\n",
    "\t\t\t\t\t\t--max_train_steps=\"2\" \\\n",
    "\t\t\t\t\t\t--num_warmup_steps=\"3\" \\\n",
    "\t\t\t\t\t\t--gradient_accumulation_steps=\"4\" \\\n",
    "\t\t\t\t\t\t--learning_rate=\"0.001\" \\\n",
    "\t\t\t\t\t\t--weight_decay=\"0.01\" \\\n",
    "\t\t\t\t\t\t--max_duration_in_seconds=\"20.0\" \\\n",
    "\t\t\t\t\t\t--min_duration_in_seconds=\"2.0\" \\\n",
    "\t\t\t\t\t\t--logging_steps=\"1\" \\\n",
    "\t\t\t\t\t\t--saving_steps=\"10000\" \\\n",
    "\t\t\t\t\t\t--per_device_train_batch_size=\"8\" \\\n",
    "\t\t\t\t\t\t--per_device_eval_batch_size=\"8\" \\\n",
    "\t\t\t\t\t\t--adam_beta1=\"0.9\" \\\n",
    "\t\t\t\t\t\t--adam_beta2=\"0.98\" \\\n",
    "\t\t\t\t\t\t--adam_epsilon=\"1e-06\" \\\n",
    "\t\t\t\t\t\t--gradient_checkpointing \\\n",
    "\t\t\t\t\t\t--mask_time_prob=\"0.65\" \\\n",
    "\t\t\t\t\t\t--mask_time_length=\"10\" \\\n",
    "\t\t\t\t\t\t--use_face \\\n",
    "\t\t\t\t\t\t--use_hands \\\n",
    "\t\t\t\t\t\t--use_pose \\\n",
    "\t\t\t\t\t\t--train_info_path=\"../sign2vec/config/info.json\" \\\n",
    "\t\t\t\t\t\t--train_data_path=\"../sign2vec/features\" \\\n",
    "\t\t\t\t\t\t--validation_info_path=\"../sign2vec/config/info.json\" \\\n",
    "\t\t\t\t\t\t--validation_data_path=\"../sign2vec/features\" \\\n",
    "\t\t\t\t\t\t--config_name=\"config.json\""
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
